[2022-07-07 00:30:47,092: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-07-07 00:30:47,094: INFO/MainProcess] mingle: searching for neighbors
[2022-07-07 00:30:48,101: INFO/MainProcess] mingle: all alone
[2022-07-07 00:30:48,131: WARNING/MainProcess] /home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-07 00:30:48,131: INFO/MainProcess] celery@Ubuntu-Workstation ready.
[2022-07-07 00:31:43,323: INFO/MainProcess] Task update_nfts_for_sale[eb444400-b62d-464f-bffc-40eed9540ddf] received
[2022-07-07 00:31:43,704: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[eb444400-b62d-464f-bffc-40eed9540ddf] succeeded in 0.38043296899999746s: None
[2022-07-07 00:32:43,317: INFO/MainProcess] Task update_nfts_for_sale[b23722c8-5114-4270-8b2c-99804132dfa2] received
[2022-07-07 00:32:43,599: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[b23722c8-5114-4270-8b2c-99804132dfa2] succeeded in 0.2806258919999891s: None
[2022-07-07 00:33:43,362: INFO/MainProcess] Task update_nfts_for_sale[09683131-b79c-4d59-95d0-88d696f05c14] received
[2022-07-07 00:33:43,597: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[09683131-b79c-4d59-95d0-88d696f05c14] succeeded in 0.2341725499999825s: None
[2022-07-07 00:34:43,402: INFO/MainProcess] Task update_nfts_for_sale[74e03a71-6341-40ab-9885-8244d9427f41] received
[2022-07-07 00:34:43,628: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[74e03a71-6341-40ab-9885-8244d9427f41] succeeded in 0.22469995199998039s: None
[2022-07-07 00:35:43,445: INFO/MainProcess] Task update_nfts_for_sale[b2b0c11e-52ac-422f-9de8-2a98c54398ab] received
[2022-07-07 00:35:43,694: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[b2b0c11e-52ac-422f-9de8-2a98c54398ab] succeeded in 0.24729375100002926s: None
[2022-07-07 00:36:32,558: INFO/MainProcess] Task marketplace.tasks.purchase_nft[7b6d294f-02bf-4aca-ac80-296d32e6c407] received
[2022-07-07 00:36:32,732: ERROR/ForkPoolWorker-4] Task marketplace.tasks.purchase_nft[7b6d294f-02bf-4aca-ac80-296d32e6c407] raised unexpected: EncodeError(TypeError('Object of type HexBytes is not JSON serializable'))
Traceback (most recent call last):
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type HexBytes is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/config/marketplace/tasks.py", line 62, in purchase_nft
    check_transaction.apply_async((token_id, tx_hash_purchase,), countdown=10, expires=30)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/messaging.py", line 166, in publish
    body, content_type, content_encoding = self._prepare(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/messaging.py", line 254, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 43, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type HexBytes is not JSON serializable
[2022-07-07 00:36:43,492: INFO/MainProcess] Task update_nfts_for_sale[7badaea9-787f-4217-9076-da6ae65bd21d] received
[2022-07-07 00:36:43,761: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[7badaea9-787f-4217-9076-da6ae65bd21d] succeeded in 0.2674751590000142s: None
[2022-07-07 00:37:43,539: INFO/MainProcess] Task update_nfts_for_sale[8e3d98a5-3841-4870-9811-208973b9590e] received
[2022-07-07 00:37:43,714: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[8e3d98a5-3841-4870-9811-208973b9590e] succeeded in 0.17439713300007043s: None
[2022-07-07 00:38:43,588: INFO/MainProcess] Task update_nfts_for_sale[b1fdb6b5-0bb4-4da0-87ee-de0964bc3f01] received
[2022-07-07 00:38:43,781: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[b1fdb6b5-0bb4-4da0-87ee-de0964bc3f01] succeeded in 0.19217496800001754s: None
[2022-07-07 00:39:43,636: INFO/MainProcess] Task update_nfts_for_sale[250bebae-2f99-4d98-b4cb-49e06e131845] received
[2022-07-07 00:39:43,814: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[250bebae-2f99-4d98-b4cb-49e06e131845] succeeded in 0.17689376299995274s: None
[2022-07-07 00:40:14,650: INFO/MainProcess] Task marketplace.tasks.purchase_nft[f12aa1eb-fbcc-430c-ae02-582453b67f78] received
[2022-07-07 00:40:14,835: ERROR/ForkPoolWorker-4] Task marketplace.tasks.purchase_nft[f12aa1eb-fbcc-430c-ae02-582453b67f78] raised unexpected: EncodeError(TypeError('Object of type HexBytes is not JSON serializable'))
Traceback (most recent call last):
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type HexBytes is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/config/marketplace/tasks.py", line 62, in purchase_nft
    check_transaction.apply_async((token_id, tx_hash_purchase,), countdown=10, expires=30)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/messaging.py", line 166, in publish
    body, content_type, content_encoding = self._prepare(
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/messaging.py", line 254, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 43, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pogginicolo98/Software-Dev/NEXID/colloquio-nexid/back-end/venv/lib/python3.9/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type HexBytes is not JSON serializable
[2022-07-07 00:40:43,676: INFO/MainProcess] Task update_nfts_for_sale[020c826a-5245-41c1-a0b9-bb3371cdc5eb] received
[2022-07-07 00:40:43,800: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[020c826a-5245-41c1-a0b9-bb3371cdc5eb] succeeded in 0.1217816700000185s: None
[2022-07-07 00:41:43,673: INFO/MainProcess] Task update_nfts_for_sale[aeabaa2c-4cf1-4668-bf7b-05a44a3bdb77] received
[2022-07-07 00:41:43,805: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[aeabaa2c-4cf1-4668-bf7b-05a44a3bdb77] succeeded in 0.13107632000003377s: None
[2022-07-07 00:42:43,727: INFO/MainProcess] Task update_nfts_for_sale[c5de8c34-6104-4fed-ba7e-6c5a5b302bde] received
[2022-07-07 00:42:43,863: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[c5de8c34-6104-4fed-ba7e-6c5a5b302bde] succeeded in 0.13402705399994375s: None
[2022-07-07 00:43:43,781: INFO/MainProcess] Task update_nfts_for_sale[8dcbf388-a5cc-4db1-9775-8cf90a0d8533] received
[2022-07-07 00:43:43,970: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[8dcbf388-a5cc-4db1-9775-8cf90a0d8533] succeeded in 0.18795196099995337s: None
[2022-07-07 00:44:43,829: INFO/MainProcess] Task update_nfts_for_sale[cdb12f9f-ec01-41a9-8df5-203ea799ab59] received
[2022-07-07 00:44:43,946: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[cdb12f9f-ec01-41a9-8df5-203ea799ab59] succeeded in 0.11546411400001944s: None
[2022-07-07 00:45:43,873: INFO/MainProcess] Task update_nfts_for_sale[aab9c1ee-ae15-449e-838e-d7d364258679] received
[2022-07-07 00:45:44,011: INFO/ForkPoolWorker-4] Task update_nfts_for_sale[aab9c1ee-ae15-449e-838e-d7d364258679] succeeded in 0.13817490399992494s: None
